insert into tags (id, name) values (DEFAULT, 'NCP');
insert into tags (id, name) values (DEFAULT, 'Yacht Charters');
insert into tags (id, name) values (DEFAULT, 'Fixed Income');
insert into tags (id, name) values (DEFAULT, 'SAP SRM');
insert into tags (id, name) values (DEFAULT, 'PPO');
insert into tags (id, name) values (DEFAULT, 'SSI');
insert into tags (id, name) values (DEFAULT, 'YUM');
insert into tags (id, name) values (DEFAULT, 'Zend');
insert into tags (id, name) values (DEFAULT, 'GNSS');
insert into tags (id, name) values (DEFAULT, 'Amazon Web Services (AWS)');
insert into tags (id, name) values (DEFAULT, 'LDPE');
insert into tags (id, name) values (DEFAULT, 'DHTMLX');
insert into tags (id, name) values (DEFAULT, 'Banquets');
insert into tags (id, name) values (DEFAULT, 'Luxury Goods');
insert into tags (id, name) values (DEFAULT, 'Xplan');
insert into tags (id, name) values (DEFAULT, 'Guest Service Management');
insert into tags (id, name) values (DEFAULT, 'CTI');
insert into tags (id, name) values (DEFAULT, 'Surgery');
insert into tags (id, name) values (DEFAULT, 'Cycle Time Reduction');
insert into tags (id, name) values (DEFAULT, 'Wind');
insert into tags (id, name) values (DEFAULT, 'Payments');
insert into tags (id, name) values (DEFAULT, 'Mac OS X Server');
insert into tags (id, name) values (DEFAULT, 'mLearning');
insert into tags (id, name) values (DEFAULT, 'Human Anatomy');
insert into tags (id, name) values (DEFAULT, 'Small Business');
insert into tags (id, name) values (DEFAULT, 'Asset Management');
insert into tags (id, name) values (DEFAULT, 'Guitar');
insert into tags (id, name) values (DEFAULT, 'Zephyr');
insert into tags (id, name) values (DEFAULT, 'AQTESOLV');
insert into tags (id, name) values (DEFAULT, 'Governmental Affairs');
