insert into tags (id, name) values (1, 'NCP');
insert into tags (id, name) values (2, 'Yacht Charters');
insert into tags (id, name) values (3, 'Fixed Income');
insert into tags (id, name) values (4, 'SAP SRM');
insert into tags (id, name) values (5, 'PPO');
insert into tags (id, name) values (6, 'SSI');
insert into tags (id, name) values (7, 'YUM');
insert into tags (id, name) values (8, 'Zend');
insert into tags (id, name) values (9, 'GNSS');
insert into tags (id, name) values (10, 'Amazon Web Services (AWS)');
insert into tags (id, name) values (11, 'LDPE');
insert into tags (id, name) values (12, 'DHTMLX');
insert into tags (id, name) values (13, 'Banquets');
insert into tags (id, name) values (14, 'Luxury Goods');
insert into tags (id, name) values (15, 'Xplan');
insert into tags (id, name) values (16, 'Guest Service Management');
insert into tags (id, name) values (17, 'CTI');
insert into tags (id, name) values (18, 'Surgery');
insert into tags (id, name) values (19, 'Cycle Time Reduction');
insert into tags (id, name) values (20, 'Wind');
insert into tags (id, name) values (21, 'Payments');
insert into tags (id, name) values (22, 'Mac OS X Server');
insert into tags (id, name) values (23, 'mLearning');
insert into tags (id, name) values (24, 'Human Anatomy');
insert into tags (id, name) values (25, 'Small Business');
insert into tags (id, name) values (26, 'Asset Management');
insert into tags (id, name) values (27, 'Guitar');
insert into tags (id, name) values (28, 'Zephyr');
insert into tags (id, name) values (29, 'AQTESOLV');
insert into tags (id, name) values (30, 'Governmental Affairs');
