insert into tags (name) values ('IT Management');
insert into tags (name) values ('GIS');
insert into tags (name) values ('CSAT');
insert into tags (name) values ('Healing');
insert into tags (name) values ('International Tax');
insert into tags (name) values ('Hotel Management');
insert into tags (name) values ('Vectorworks');
insert into tags (name) values ('QuickBooks');
insert into tags (name) values ('OOP');
insert into tags (name) values ('Protein Expression');
insert into tags (name) values ('PWM');
insert into tags (name) values ('XSS');
insert into tags (name) values ('PVTsim');
insert into tags (name) values ('Athletic Training');
insert into tags (name) values ('IGMP Snooping');
insert into tags (name) values ('XPS');
insert into tags (name) values ('VHF');
insert into tags (name) values ('OCP');
insert into tags (name) values ('Advertising');
insert into tags (name) values ('Ffmpeg');
insert into tags (name) values ('Information Technology');
insert into tags (name) values ('Aerospace Industries');
insert into tags (name) values ('RMX');
insert into tags (name) values ('Fertilizers');
insert into tags (name) values ('Yoga');
insert into tags (name) values ('Frozen Food');
insert into tags (name) values ('IBM Content Manager');
insert into tags (name) values ('PFlow');
insert into tags (name) values ('IOT');
insert into tags (name) values ('Oozie');
